# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hutricot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/17 15:39:42 by hutricot          #+#    #+#              #
#    Updated: 2018/07/19 20:56:24 by hutricot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = ft_atoi.c \
	  ft_putchar.c \
	  ft_putnbr.c \
	  ft_putstr.c \
	  ft_add.c \
	  ft_mod.c \
	  ft_sub.c \
	  ft_mul.c \
	  ft_div.c \
	  ft_usage.c \
	  ft_strcmp.c \
	  main.c 

all : $(NAME)

$(NAME) :
	gcc -o $(NAME) $(SRC)
clean :
	rm -f $(NAME)
re : clean all
